-- بيانات أولية مُولَّدة من نسخة Artifact الحالية
begin;

-- اللجان
insert into committees (id, name, purpose, head_title, note) values ('c_social', 'اللجنة الاجتماعية', 'تحقيق التكافل الاجتماعي: حصر المحتاجين من أبناء العائلة، سد احتياجاتهم الأساسية، والصرف عليهم.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_communication', 'لجنة التواصل', 'تعزيز الروابط بين أفراد العائلة: تنظيم اللقاءات الدورية، تحديث قاعدة بيانات الأفراد، وإدارة شبكات التواصل الداخلية.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_finance_endowments', 'لجنة تنمية الموارد المالية والأوقاف', 'تنمية الموارد المالية للصندوق: إيجاد موارد مالية، تأسيس أوقاف، وتحقيق الاستدامة المالية.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_development', 'لجنة التطوير والتأهيل', 'تطوير وتأهيل أفراد العائلة: البناء العقلي والمهني، تجاوز تحديات سوق العمل، وتنمية المهارات.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_marriage_loan_review', 'برنامج إقراض الزواج / الفحص والتحصيل', 'دعم أفراد العائلة الراغبين في الزواج: دراسة الأوضاع، التوصية بالقروض الحسنة، ومتابعة التحصيل.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_marriage_loan_credit', 'برنامج إقراض الزواج / الائتمان', 'اعتماد صرف القروض لراغبي الزواج: دراسة الطلبات، اعتماد الصرف، وإعداد التقارير المالية الدورية.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_heritage', 'تراث العائلة العلمي', 'توثيق تراث العائلة العلمي بجميع أشكاله: المقروء، المطبوع، المخطوط، المرئي، والمسموع، وحفظه بطرق حديثة.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_excellence', 'جائزة التميز', 'تحفيز أبناء العائلة وتكريم المتميزين: الإشراف على الجائزة، وضع معايير التميز، وترشيح المتميزين.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_governance', 'المراجعة والحوكمة', 'رفع مستوى حوكمة الصندوق: مراجعة الأنظمة واللوائح، ومتابعة تطبيق اللجان لها.', '', '');
insert into committees (id, name, purpose, head_title, note) values ('c_executive', 'اللجنة التنفيذية', 'متابعة أعمال لجان الصندوق واقتراح الخطط التصحيحية، وجمع تقارير اللجان وإعداد العروض لمجلس الأمناء.', 'المدير التنفيذي للصندوق', 'أعضاء اللجنة هم مقررو بقية اللجان بحكم مناصبهم تلقائيًا.');

-- إضافة أعضاء الإدارة التنفيذية الثلاثة (طارق - رئيس، سامي - عضو) إلى قائمة الحسابات إن لم تكن موجودة

-- الحسابات (رموز الدخول مُجزَّأة bcrypt، لا تُخزَّن كنص صريح)
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_246316', 'سليمان الدويش', '$2b$10$WgJZVsAdxDLct61Qkktv.urgC5ns5LDYy7IrL9VwRKKOcQy3GjlGS', true, false, true, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_809570', 'الشيخ إبراهيم بن عبدالله بن إبراهيم الدويش', '$2b$10$.2HYRXfY5gcX7M4shDfRWOUdWFeNB5QqGUM0Nao.46W/iDuB7G7.K', false, true, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_191161', 'أ. أحمد بن محمد بن صالح الدويش', '$2b$10$OYk3.X8wJ1OuDLEvSpiZMeGXBr50zFgyw35POmPmjtzfEtsp5BElS', false, true, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_542417', 'م. عبدالله بن أحمد بن عبدالرزاق الدويش', '$2b$10$4rPMd546.m.qiDid1x4VFODFTgPCBBfuVEbVReWGx3MYio9HTvv5G', false, true, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_131244', 'د. عبدالله بن سليمان بن محمد الدويش', '$2b$10$uH1RzOCOxR4fGXNaAZCFl.fQJjAoqSeHOGrNqaqc5lAcHQgZEeYfK', false, true, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_329258', 'د. صالح بن أحمد بن جاسر الضويحي', '$2b$10$hsy2g5JnMAcRXDpWDVbF0.bOYWKruMkkIC/MwudQYItf0lu/B9LEW', false, true, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_629903', 'يزيد بن فهد بن عبدالله الصالح', '$2b$10$wAoMpibrPiW1EOFmsXOU3Oy7AuXohUmMPNnMdwVP0nuC1aofCeyAW', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_127824', 'أحمد بن محمد بن صالح الصالح', '$2b$10$.2a1RVH3Z6JT2P2JY9.r9OEAkOT1lGEds/TT1UfUA/Ah24TaVST2q', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_308496', 'إبراهيم بن عبدالله بن صالح بن إبراهيم العبدالعزيز', '$2b$10$ppfeeT6P1qG6MvqVaHqsoOMSbtVRWv/V5nOWzSDxjPDPXlaXQ5Sim', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_539898', 'صالح بن حمود بن أحمد البراهيم', '$2b$10$HRFtKG3NdC7TmDIcphEuC.3bpz6pB6vB1QgeX8NlyMp0fqNB4wU5a', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_571029', 'عبدالرزاق بن عبدالعزيز بن عبدالرزاق العبدالرزاق', '$2b$10$3vFlppL73EaicGiLtkxgd.XxH1PJumCc6zWAEypsDoIAV96lueGwe', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_391704', 'محمد بن أحمد بن محمد العبدالرزاق', '$2b$10$FmQjglMWD1YFWMLfU285Z..08HA3szvEFSPVDuv.pOlymN1dQiNfG', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_895667', 'محمد بن سلطان بن محمد الصالح', '$2b$10$v0zzY.W/jkpbaNdpZqaTsOX4JrQCZTdHJsJQ5HM7QOZwqlu8U2d5K', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_832052', 'أيوب بن عبدالله بن عبدالعزيز البراهيم', '$2b$10$1q9tB7rPxmcQ1HlMugo5S.x12iGPOkFB/acGYmq2NA8C7049sYHuG', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_456778', 'ثامر بن عبدالعزيز بن عبدالرزاق العبدالرزاق', '$2b$10$c18oAT/RG3tKh8TvXiRg/eyJ4yB4gDzqoPL5CZTFbtd9cYQtuNVwS', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_263032', 'عبدالعزيز بن طلال بن تركي الضويحي', '$2b$10$BItFdI53XYg9YPXSFFmBQ.gYchhx7AQDBMa8NXKdeivtUYiU5bM/6', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_900581', 'عبدالله إبراهيم بن عبدالله بن صالح العبدالعزيز', '$2b$10$RPMr8TPDv1IQyeqfLJRHve/FR74SQNI1iL.fPS7.x/8AoljgEZKdi', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_207175', 'محمد بن نايف بن محمد الصالح', '$2b$10$HZ1l6XYZ/UPYUL5PQ06hj.N1xs5q0h48Z49e3nZUUeQa3XMWQjnm2', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_498382', 'عبدالله بن أحمد بن عبدالرزاق الصالح', '$2b$10$Etmqldq.p800.QFx/FVXc.VOxdsRjwDCfyBSe9UHTl/vv5gYtxhpC', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_476417', 'تركي بن سلطان بن محمد الصالح', '$2b$10$Gz0pTZYKjPnB0ZtLT3jEQujvP9M4Ibsxr0glmVkjEKYzk1r1sbG82', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_733052', 'صالح بن محمد بن راشد العبدالرزاق', '$2b$10$961l2sk0l8GACJSH42IrrOwZwrJChPHn6Ng9ZsK4c2dDake3CnwC2', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_946335', 'عمر بن عبدالعزيز الجاسر الضويحي', '$2b$10$zOMVraNJGA6o7FVKNMt8f.nopRg76pczbkGwiK3kYuHTesgtqnadO', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_865179', 'محمد بن صالح بن عبدالرزاق الصالح', '$2b$10$aqpa7wF1S7z2Y8.y6w7RNuofGr4pv6O70R23MyYvDVrRlvTTm1HsC', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_662275', 'سلطان بن محمد بن عبدالرزاق الصالح', '$2b$10$pp/fIbwBZg05OKOGWJCl8.YOh/f3E7EuG.vbFr0uYDc1XgAq2wWwq', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_496922', 'ماجد بن علي بن سليمان الضويحي', '$2b$10$sK7AJaviXyImeQjwZXktzeMRR1ipI5r.MXCrSWpXjeHoZCHka5EjG', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_678856', 'عبدالله بن إبراهيم بن عبدالله البراهيم', '$2b$10$SanNc6hiFdHZcYFWknpLU.MQuHU2U4hsUQ2r.CXJqwK92/CDm/Q6i', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_969693', 'عبدالسلام بن عبدالعزيز بن سليمان العبدالرزاق', '$2b$10$9G36.aaBFK7vPj16uzAFjOUJfPT1Ql5UMeAR/BXG8NAV80NVor6iy', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_705397', 'نايف بن محمد بن سليمان الصالح', '$2b$10$0NjpZiI/jCW/lLWPWv0Q8OC3n9Afw6CK7TllYDaIs.SnvA.SRNiyy', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_838797', 'عبدالله بن سليمان بن فهد العبدالرزاق', '$2b$10$a1Rr8g7woUvGlFOq7Fe5J.BLgcrAxIcpa9ebZT5FaeOuQPQh1e4GC', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_148050', 'بدر بن أحمد بن محمد العبدالرزاق', '$2b$10$4s/et.xVghDzOw/qw80dIuVIH0gCXVtk96BN0qxs/TdC4LIuL/Rsm', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_910620', 'سليمان بن فهد بن عبدالله العبدالرزاق', '$2b$10$d0pqRJv1bAq4MWvAPVg6yetYHgvnovqKQgphjNuv/PbJRjG29/7Ui', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_183667', 'عبداللطيف بن عبدالله بن صالح العبدالعزيز', '$2b$10$4aAKirfxyO7HARi15HnXa.vEQKn4pdTUQ7QrlNLDDEc3VS49bptUK', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_205907', 'سليمان بن فهد بن سليمان بن محمد العبدالرزاق', '$2b$10$WfYceo7xOTlcWF/szRpF5.NeL6kZkXpyFswNl/dLX5W/8UU1oFjte', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_391476', 'ماجد بن عبدالله بن عبداللطيف الصالح', '$2b$10$FB0rCafdMSsw/jTDaLFneO/9wQrRQcQe5uywOljAlycoja/Slj6eG', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_766563', 'خالد بن عبدالمحسن بن محمد الأحمد العبدالرزاق', '$2b$10$OniXxDX5wF/6Xkfh22eEtOelALt0D4CtIcqNY7yFquKzYGZ.10qgq', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_270555', 'د. محمد بن عبدالله بن إبراهيم البراهيم', '$2b$10$HDDhrSnldoYLpA8iX5MqkOkm8DvDK4HA0MbFhxZzhEYqYPH8T2i4i', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_472528', 'د. أيمن بن أحمد بن عبد الله البراهيم', '$2b$10$qlb2duJCFkUbSRfhryaItuXgEm00yPCqmVatjOJRLgECcqm4AWbIu', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_802729', 'د. أحمد بن إبراهيم بن حمد الضويحي', '$2b$10$b4NbnF4B4O7b4RRfAuVb3OADE/tYTlHX6Xgw4KzwlXe/GF9HNOOO.', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_835911', 'د. صالح بن يوسف بن عبدالرحمن الصالح', '$2b$10$7MYKVPZqE3.OHE1Pef/4IuugCfA9cm8x2bPZSuha2wJQ38RBd.v7K', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_738720', 'عبدالعزيز بن سليمان بن عبدالعزيز بن أحمد العبدالرزاق', '$2b$10$nWe1oeiS8/s1iiE/7BEN9emVyWcKZDshWazjDTl2L.lnfTtVT7vTW', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_660086', 'ا.د. أحمد بن عبدالله بن محمد بن صالح الضويحي', '$2b$10$nXAzeFIL1hwtJTv0H4liAOTlRfw89FlM0eO.6DDRzBYVHmAcKLM3e', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_271339', 'يزيد بن عبدالرحمن بن سليمان بن عبدالرزاق العبدالرزاق', '$2b$10$2Xzg0z.ojuOkRqdrkGHCZuDzfQ5hA9jyhUHPDf2hADAKnorVTS8f2', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_497887', 'د. خالد بن إبراهيم بن عبداللطيف الصالح', '$2b$10$7TzW30zRY5FO3tMF4TH/0O4Ds7911B7pyHT64sOzXOJ5tT.1mO7bS', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_771088', 'أ. د. عبدالعزيز بن سليمان بن عبدالرزاق العبدالرزاق', '$2b$10$5RNbaqxy1wkWfV0ddf0bsu8LGa0SsOL6czQO.KSZrmqFXzotWJfXG', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_330283', 'طلال بن تركي بن ضويحي بن عبدالعزيز الضويحي', '$2b$10$XuwCxoos6RPZY8QRULsaA.Y/h3xRqkmnkffMn5NxpwZukIy8NB3mm', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_983794', 'د. عبدالسلام بن محمد بن عبدالعزيز بن إبراهيم العبدالعزيز', '$2b$10$jYWfCZnW/4ZvGh/zJf5EVOV5LwyR5MrnIjmq/FisXIpBmGsi.ACfi', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_340174', 'د. خالد بن صالح بن عبدالرحمن البراهيم', '$2b$10$4CRURFZCdXKpN3ZID6iM0eueDjnIXw/LvteLZUVj21cBFadj4Ajne', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_944151', 'صالح بن سليمان بن عبدالرزاق الصالح', '$2b$10$VjcENi.fKWQBYh1bKElwjuS/k405sPGlFl8Nnn7QaWRq1MEH9ABo2', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_520651', 'د. عبدالله بن سليمان بن محمد العبدالرزاق', '$2b$10$tmoE4fhYYUBFJrdaZ/TQcO8urV2CHPrXdqtWRZXj5VUWSkWmvukia', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_169403', 'سليمان بن راشد بن سليمان العبدالرزاق', '$2b$10$8aOufIkPIroG7NLsGUkteuU1MXbVCMFvv1VQ/zn5pJyycbIm.Wz5G', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_694731', 'د. منصور بن عثمان بن محمد الضويحي', '$2b$10$yeJTWHmhSa8sDTPkfRGUju.0WGI6L.lVJB5jwdeuiZ4hGCdLudS46', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_322955', 'محمد بن عبدالله بن عبدالعزيز الإبراهيم', '$2b$10$619K..4WUfeXuLA3ZsyU8.d6rq896uU8SXooCY6jYw9R5DBfHz19S', false, false, false, false);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_exec_tariq', 'طارق الدويش', '$2b$10$KJQPiHRlj0iRgoEEp7hBiuNWu6Ri9Q3CFu2IRh3OJfyb5UOn0UeGq', false, false, true, true);
insert into accounts (id, name, pin_hash, is_admin, is_trustee, is_executive, is_executive_head) values ('acc_exec_sami', 'سامي احمد الدويش', '$2b$10$Rga5FgxYt17geUneKrT0SuZTDKvdsg5a/DUlINx7d5Aofp0tX62La', false, false, true, false);

commit;
